name: Linux Build

on:
  push:
    branches-ignore:    
      - 'main'
    tags:
      - 'v*'

jobs:
  Build_Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: useed_linux
          path: useed_linux
  Build_MacOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: useed_macos
          path: useed_macos
  Build_Windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: useed.exe
          path: useed.exe
  Publish:
    needs:
      - Build_Linux
      - Build_MacOS
      - Build_Windows
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: useed_linux
      - name: Download MacOS artifact
        uses: actions/download-artifact@v3
        with:
          name: useed_macos
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: useed.exe
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            - useed_linux
            - useed_macos
            - useed.exe