name: Linux Build

on:
  push:
    branches-ignore:    
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            useed