name: MacOS Build

on: push
#   push:
#     branches-ignore:    
#       - 'main'
#     tags:
#       - 'v*'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
